'use client';
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { ShieldCheck, Files, ListChecks, Activity, History, ChevronRight, Check, AlertTriangle, Search, Download, Fingerprint, CircleHelp, Plus, X, Upload, FileText, ArrowUpRight, RotateCcw, Pencil, Link2Off } from 'lucide-react';
import { evaluate, summarize, type Status, type Requirement, type EvidenceDocument } from '../lib/compliance';
import { initialWorkspace, addAudit, invalidate, type Workspace } from '../lib/workspace';
import { extractRequirements, readDocument } from '../lib/documents';

const tabs=[{name:'Compliance review',icon:ListChecks},{name:'Documents',icon:Files},{name:'Requirements',icon:FileText},{name:'Risk intelligence',icon:Activity},{name:'Audit trail',icon:History}];
const statuses:Status[]=['Compliant','Non-compliant','Needs review'];
const statusClass=(s:string)=>s.toLowerCase().replaceAll(' ','-');
function Badge({status}:{status:Status}) {return <span className={'status '+statusClass(status)}>{status==='Compliant'?<Check size={13}/>:<AlertTriangle size={13}/>} {status}</span>;}
function download(name:string,content:string,type='application/json') {const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}) {
 const ref=useRef<HTMLDivElement>(null);const closeRef=useRef(close);closeRef.current=close;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null; ref.current?.focus();const handler=(event:KeyboardEvent)=>{if(event.key==='Escape')closeRef.current();if(event.key==='Tab'){const elements=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,a[href]');if(!elements?.length)return;const first=elements[0],last=elements[elements.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus();};},[]);
 return <div className="modal-backdrop"><div className="modal" ref={ref} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1}><header><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={close}><X size={20}/></button></header>{children}</div></div>;
}

export default function Bidguard() {
 const [state,setState]=useState<Workspace>(initialWorkspace);
 const [ready,setReady]=useState(false); const [tab,setTab]=useState('Compliance review');
 const [selected,setSelected]=useState('REQ-002');const [filter,setFilter]=useState('All requirements');const [query,setQuery]=useState('');
 const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [modal,setModal]=useState<'new'|'report'|'decision'|null>(null);const [source,setSource]=useState<{doc:EvidenceDocument;page:number;quote?:string}|null>(null);
 const [edit,setEdit]=useState<Requirement|null>(null);const [role,setRole]=useState<'tender'|'bid'>('bid');
 const [draft,setDraft]=useState<{doc:EvidenceDocument;requirements:Requirement[]}|null>(null);
 const [officer,setOfficer]=useState('');const [reason,setReason]=useState('');const [reviewStatus,setReviewStatus]=useState<Status>('Needs review');
 const [decisionStatus,setDecisionStatus]=useState('Request clarification'); const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const raw=localStorage.getItem('bidguard-workspace-v1');if(raw){const value=JSON.parse(raw);if(value.version===1&&Array.isArray(value.requirements)&&Array.isArray(value.documents)&&Array.isArray(value.audit)&&value.reviews)setState(value);}}catch{setError('Saved workspace could not be loaded. The sample is available.');}setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('bidguard-workspace-v1',JSON.stringify(state));}catch{setError('Browser storage is full or unavailable. Export your assessment before closing this page.');}},[state,ready]);
 const results=useMemo(()=>evaluate(state.requirements,state.documents),[state.requirements,state.documents]);
 const summary=summarize(results);const active=results.find(r=>r.requirement.id===selected)||results[0];
 const visible=results.filter(r=>(filter==='All requirements'||r.status===filter)&&(r.requirement.title+' '+r.requirement.id).toLowerCase().includes(query.toLowerCase()));
 const commit=(next:Workspace,action:string,detail:string,actor='Local operator')=>{setState(addAudit(next,actor,action,detail));setError('');setMessage(action);};
 const inspect=(name:string,page:number,quote?:string)=>{const doc=state.documents.find(d=>d.name===name);if(doc)setSource({doc,page,quote});};
 const exportJson=()=>{download('bidguard-assessment.json',JSON.stringify({exportedAt:new Date().toISOString(),workspace:state,assessment:results,summary,limitations:['Document checks only; no live portal verification','Local editable audit history; not a tamper-proof record','Rule-based extraction; no LLM or OCR enabled']},null,2));setMessage('Assessment and evidence exported.');};
 async function importFiles(files:FileList|null){
  if(!files?.length)return;setBusy(true);setError('');setMessage('Reading document text…');
  try {
   if(role==='tender'&&files.length>1)throw new Error('Import one tender at a time.');
   if(files.length>10)throw new Error('Import up to 10 documents at a time.');
   const docs:EvidenceDocument[]=[];
   for(const file of Array.from(files)){const doc=await readDocument(file,role);if([...state.documents,...docs].some(d=>d.name===doc.name||d.hash===doc.hash))throw new Error(`“${doc.name}” is already present. Use a distinct filename for a revised document.`);docs.push(doc);}
   if(role==='tender'){const doc=docs[0];const requirements=extractRequirements(doc);if(!requirements.length)throw new Error('No candidate clauses were detected. Add explicit “must”, “shall”, or “Minimum experience: 5 years” clauses to the tender text.');setDraft({doc,requirements});setMessage('Review the extracted clauses before applying them.');}
   else {commit(invalidate({...state,documents:[...state.documents,...docs]}),'Bid documents imported',`${docs.length} documents added. Prior officer reviews and final decision cleared because evidence changed.`);setTab('Compliance review');}
  }catch(e){setError(e instanceof Error?e.message:'Import failed.');setMessage('');}finally{setBusy(false);if(fileRef.current)fileRef.current.value='';}
 }
 function saveReview(){if(!active)return;if(!officer.trim()||reason.trim().length<10){setError('Enter your name and a review reason of at least 10 characters.');return;}const old=state.reviews[active.requirement.id]?.status||active.status;commit({...state,decision:undefined,reviews:{...state.reviews,[active.requirement.id]:{status:reviewStatus,reason:reason.trim(),actor:officer.trim(),time:new Date().toISOString()}}},'Officer review recorded',`${active.requirement.id}: ${old} → ${reviewStatus}. ${reason.trim()}`,officer.trim());setReason('');}
 const snapshot=useRef({results,summary});snapshot.current={results,summary};
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:'read_bid_assessment',description:'Read current document compliance findings and risk. Does not qualify or disqualify a bidder.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');return snapshot.current;}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return()=>lifecycle.abort();
 },[]);

 return <><div className="shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-icon"><ShieldCheck size={25}/></span><span>BIDGUARD<small>PROCUREMENT INTELLIGENCE</small></span></a><div className="workspace"><span className="workspace-icon">BG</span><div>Procurement workspace<small>SIH 2026 · Prototype</small></div></div><p className="nav-label">WORKSPACE</p><nav aria-label="Workspace navigation">{tabs.map(t=><button key={t.name} className={tab===t.name?'active':''} aria-current={tab===t.name?'page':undefined} onClick={()=>setTab(t.name)}><t.icon size={18}/>{t.name}{t.name==='Compliance review'&&<span>{summary.total}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="secure"><Fingerprint size={22}/><b>Evidence. Not assumptions.</b><p>Every finding has a source.<br/>Every decision stays human.</p></div><div className="profile"><span>PO</span><div>Procurement Officer<small>Saved on this browser only</small></div></div></div></aside>
 <main><header className="topbar"><div>Workspace <ChevronRight size={14}/> Assessment <ChevronRight size={14}/> <b>{state.sample?'BG-2026-014':'Custom tender'}</b></div><span className="demo-badge"><i/>{state.sample?'SAMPLE WORKSPACE':'LOCAL WORKSPACE'}</span></header><section className="content"><div className="page-heading"><div><p className="eyebrow">BID EVALUATION / EVIDENCE WORKBENCH</p><h1>{tab==='Compliance review'?'Compliance workbench':tab}<span>{state.decision?.status||'In review'}</span></h1><p>{state.name}</p></div><div className="toolbar"><button className="button" onClick={()=>setModal('new')}><Plus size={16}/> New assessment</button><button className="button primary" onClick={()=>setModal('report')}><Download size={16}/> Export report</button></div></div>
 {error&&<div role="alert" className="error">{error}<button className="dismiss" aria-label="Dismiss error" onClick={()=>setError('')}><X size={15}/></button></div>}{message&&<div className="feedback" role="status">{message}<button className="dismiss" aria-label="Dismiss message" onClick={()=>setMessage('')}><X size={15}/></button></div>}
 <div className="tender-strip"><span className="bidder-avatar">{state.bidder.split(' ').slice(0,2).map(s=>s[0]).join('')}</span><div><small>SELECTED BIDDER</small><b>{state.bidder}</b></div><div className="strip-detail"><small>EVIDENCE FILES</small><b>{state.documents.filter(d=>d.role==='bid').length} documents</b></div><div className="strip-detail"><small>OFFICER REVIEWS</small><b>{Object.keys(state.reviews).length} / {summary.total} checks</b></div><button className="text-link" onClick={()=>setTab('Documents')}>Manage documents <ArrowUpRight size={16}/></button></div>
 {tab==='Compliance review'&&<><div className="stats"><div><small>Requirements checked</small><strong>{summary.total}<span>/ {summary.total}</span></strong><p>{new Set(state.requirements.map(r=>r.category)).size} compliance categories</p></div><div><small><i className="dot green"/> Compliant</small><strong>{summary.pass}<span className="green-text">Evidence matched</span></strong><p>Document-based checks only</p></div><div><small><i className="dot red"/> Non-compliant</small><strong>{summary.fail}<span className="red-text">Action required</span></strong><p>Thresholds not satisfied</p></div><div><small><i className="dot amber"/> Needs review</small><strong>{summary.review}<span className="amber-text">Officer attention</span></strong><p>Missing or unverified evidence</p></div></div><div className="review-layout"><section className="matrix panel"><div className="panel-heading"><div><h2>Compliance matrix</h2><p>Automated findings · Officer reviews appear separately</p></div><span className="count">{results.length} checks</span></div><div className="matrix-controls"><label className="search"><Search size={16}/><input aria-label="Search requirements" placeholder="Search requirements…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter by automated status" value={filter} onChange={e=>setFilter(e.target.value)}>{['All requirements',...statuses].map(s=><option key={s}>{s}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>REQUIREMENT</th><th>STATUS</th><th>EVIDENCE</th><th/></tr></thead><tbody>{visible.map(r=><tr key={r.requirement.id} className={active?.requirement.id===r.requirement.id?'selected':''} onClick={()=>{setSelected(r.requirement.id);setReason('');}}><td><small>{r.requirement.id} · {r.requirement.category}</small><button className="row-title" onClick={()=>{setSelected(r.requirement.id);setReason('');}}>{r.requirement.title}</button>{state.reviews[r.requirement.id]&&<small className="reviewed">Officer: {state.reviews[r.requirement.id].status}</small>}</td><td><Badge status={r.status}/></td><td><span className="evidence-cell">{r.evidence[0]?`Page ${r.evidence[0].page}`:'Missing'}<small>{r.evidence.length} source{r.evidence.length!==1?'s':''}</small></span></td><td><ChevronRight size={15}/></td></tr>)}</tbody></table>{!visible.length&&<div className="empty">{results.length?'No requirements match this filter.':'Import a tender in Documents to begin.'}</div>}</div><div className="matrix-footer"><ShieldCheck size={15}/> Deterministic checks · Final decision stays with you</div></section>
 {active&&<aside className="evidence panel"><div className="panel-heading"><div><p className="eyebrow">EVIDENCE INSPECTOR / {active.requirement.id}</p><h2>{active.requirement.title}</h2></div><Files size={20}/></div><div className="evidence-body"><Badge status={active.status}/><p className="explanation">{active.reason}</p><div className="comparison"><div><small>REQUIRED</small><b>{active.requirement.minimum??'Verified'} {active.requirement.unit}</b></div><div><small>OBSERVED</small><b className={active.status==='Non-compliant'?'red-text':''}>{active.values.length?active.values.join(' / '):'Unverified'} {active.values.length?active.requirement.unit:''}</b></div></div><button className="source-link" onClick={()=>inspect(active.requirement.source,active.requirement.page)}>Tender clause · Page {active.requirement.page} <ArrowUpRight size={13}/></button>{active.evidence.map((e,i)=><div className="source" key={i}><div><Files size={15}/><b>{e.document}</b><span>p. {e.page}</span></div><blockquote>“{e.quote}”</blockquote><button className="source-link" onClick={()=>inspect(e.document,e.page,e.quote)}>View source page <ArrowUpRight size={12}/></button></div>)}{!active.evidence.length&&<div className="notice">No evidence found. Add the supporting document to continue.</div>}<div className="officer-note"><CircleHelp size={17}/><p>Threshold compliance does not establish document authenticity. No government portals are connected.</p></div><div className="review-form"><h2>Officer review</h2>{state.reviews[active.requirement.id]&&<div className="notice"><b>{state.reviews[active.requirement.id].status}</b><br/>{state.reviews[active.requirement.id].reason}<br/><small>{state.reviews[active.requirement.id].actor}</small></div>}<label className="field">Reviewer name<input value={officer} onChange={e=>setOfficer(e.target.value)} placeholder="Your name" maxLength={100}/></label><label className="field">Reviewed status<select value={reviewStatus} onChange={e=>setReviewStatus(e.target.value as Status)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Reason and verification reference<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain your assessment and supporting evidence…" maxLength={2000}/></label><button className="button primary full" onClick={saveReview}>Record review</button></div></div></aside>}</div><div className="decision-callout"><div><h2>Ready for an officer decision?</h2><p>Review the findings, then record qualification or request clarification.</p></div><button className="button" disabled={!results.length} onClick={()=>{setReason('');setModal('decision');}}>Record decision <ChevronRight size={16}/></button></div></>}
 {tab==='Documents'&&<section className="panel page-panel"><div className="panel-heading"><div><h2>Document workspace</h2><p>Text stays in this browser. Import PDF or UTF-8 TXT files.</p></div><Upload size={20}/></div><div className="section-body"><div className="notice">PDF text extraction preserves page references. Scanned PDFs need OCR before import. 10 MB / 100 pages per file. Adding evidence clears prior officer decisions so they can be reviewed again.</div><label className="field">Document type<select value={role} onChange={e=>setRole(e.target.value as 'tender'|'bid')}><option value="bid">Bidder supporting documents</option><option value="tender">Tender — extract draft requirements</option></select></label><label className="upload-label">Choose documents<input ref={fileRef} className="file-input" type="file" accept=".pdf,.txt" multiple={role==='bid'} disabled={busy} onChange={e=>void importFiles(e.target.files)}/></label>{busy&&<p role="status">Extracting page text and calculating document fingerprint…</p>}<div className="document-list">{state.documents.map(doc=><div className="document-row" key={doc.id}><FileText size={25}/><div><b>{doc.name}</b><p>{doc.role==='tender'?'Tender':'Bid evidence'} · {doc.pages.length} page{doc.pages.length!==1?'s':''} · {doc.hash?`SHA-256 ${doc.hash.slice(0,12)}…`:'Synthetic sample'}</p>{doc.pages.some(p=>!p.trim())&&<p className="amber-text">Some pages have no extracted text; inspect the original for scanned content.</p>}</div><button className="button" onClick={()=>setSource({doc,page:1})}>Read text</button><button className="icon-button" aria-label={'Download '+doc.name} onClick={()=>download(doc.name.replace(/\.pdf$/i,'.txt'),doc.pages.join('\f'),'text/plain')}><Download size={18}/></button></div>)}</div>{!state.documents.length&&<div className="empty">No documents yet. Upload a tender first, then the bidder documents.</div>}</div></section>}
 {tab==='Requirements'&&<section className="panel page-panel"><div className="panel-heading"><div><h2>Tender requirements</h2><p>Confirm every rule against the source clause before relying on the assessment.</p></div></div><div className="section-body"><div className="notice">The extractor proposes explicit minimum rules for experience, turnover, local content, warranty and completed projects. Other clauses require manual review. These are tender-specific demo rules, not a statement of procurement law.</div><div className="table-scroll"><table><thead><tr><th>CLAUSE</th><th>RULE</th><th>WEIGHT</th><th/></tr></thead><tbody>{state.requirements.map(r=><tr key={r.id}><td><small>{r.id} · {r.category}</small>{r.title}<button className="source-link" onClick={()=>inspect(r.source,r.page)}>Source · p. {r.page}</button></td><td>{r.kind==='minimum'?`≥ ${r.minimum} ${r.unit}`:r.kind==='portal'?'Registry verification':'Manual interpretation'}</td><td>{r.weight}</td><td><button className="icon-button" aria-label={'Edit '+r.id} onClick={()=>setEdit({...r})}><Pencil size={16}/></button></td></tr>)}</tbody></table></div>{!state.requirements.length&&<div className="empty">Import a tender in Documents to extract candidate requirements.</div>}</div></section>}
 {tab==='Risk intelligence'&&<><div className="risk-layout page-panel"><section className="panel"><div className="panel-heading"><h2>Document risk index</h2><Activity size={18}/></div><div className="section-body"><div className="risk-score">{summary.risk}<span>/100</span></div><Badge status={summary.risk>40?'Non-compliant':'Needs review'}/><h2 className="risk-level">{summary.level} risk · {summary.total} rules</h2><div className="risk-bar"><span style={{width:`${summary.risk}%`}}/></div><p className="muted">An explainable review-priority score, not a fraud prediction or bidder rating.</p><p className="muted">Pass = 0; fail = full rule weight; review = half weight. Total points ÷ total rule weight × 100, rounded.</p><p className="muted">0–20 Low · 21–40 Medium<br/>41–60 High · 61–100 Critical</p></div></section><section className="panel"><div className="panel-heading"><h2>What contributes to the score</h2><span className="count">Automated findings</span></div><div className="section-body">{results.filter(r=>r.risk>0).map(r=><div className="risk-row" key={r.requirement.id}><div><button className="row-title" onClick={()=>{setSelected(r.requirement.id);setTab('Compliance review');}}>{r.requirement.title} <ArrowUpRight size={12}/></button><p>{r.reason}</p></div><b>+{r.risk}</b></div>)}{!results.some(r=>r.risk>0)&&<p>No risk points from current rules. Authenticity remains unverified.</p>}<div className="notice">Officer reviews do not overwrite the automated risk index. Original findings remain visible in the report.</div></div></section></div><section className="panel page-panel"><div className="panel-heading"><h2>Registry connections</h2><Link2Off size={18}/></div><div className="section-body registry-grid">{['GeM','GSTN','Udyam / MSME','PAN / Income Tax','MCA21','EPFO / ESIC','DigiLocker','NSIC / Startup India'].map(p=><div key={p}><b>{p}</b><span>Not connected</span></div>)}</div></section></>}
 {tab==='Audit trail'&&<section className="panel page-panel"><div className="panel-heading"><div><h2>Assessment history</h2><p>Local activity record · Not an authenticated or tamper-proof audit system</p></div><button className="button" onClick={exportJson}><Download size={15}/> Export history</button></div><div className="section-body">{[...state.audit].reverse().map(a=><div className="audit-row" key={a.id}><History size={18}/><div><b>{a.action}</b><p>{a.detail}</p><small>{a.actor} · {new Date(a.time).toLocaleString()}</small></div></div>)}</div></section>}
 <div className="bottom-note"><ShieldCheck size={16}/> {state.sample?'Synthetic sample data · ':''}Local browser storage · Rule-based extraction · No live portal verification</div></section></main></div>
 {modal==='new'&&<Modal title="Create an assessment" close={()=>setModal(null)}><p className="muted">Start an empty workspace or reload the sample. This replaces the current browser workspace; export it first if you want to keep it.</p><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const next:Workspace={version:1,name:String(data.get('tender')).trim(),bidder:String(data.get('bidder')).trim(),sample:false,requirements:[],documents:[],reviews:{},audit:[]};if(!next.name||!next.bidder)return;commit(next,'Assessment created',next.name);setModal(null);setTab('Documents');setSelected('');setFilter('All requirements');setQuery('');}}><div className="form-grid"><label className="field">Tender name<input name="tender" required maxLength={150} placeholder="Tender title"/></label><label className="field">Bidder name<input name="bidder" required maxLength={150} placeholder="Company name"/></label></div><div className="toolbar"><button type="button" className="button" onClick={exportJson}><Download size={15}/> Export current</button><button className="button primary" type="submit"><Plus size={15}/> Create workspace</button><button type="button" className="button" onClick={()=>{setState(initialWorkspace());setModal(null);setTab('Compliance review');setSelected('REQ-002');setQuery('');setFilter('All requirements');setMessage('Sample workspace restored.');}}><RotateCcw size={15}/> Load sample</button></div></form></Modal>}
 {modal==='report'&&<Modal title="Export assessment report" close={()=>setModal(null)}><div className="notice"><b>{state.bidder}</b><br/>{summary.pass} compliant · {summary.fail} non-compliant · {summary.review} need review<br/>Document risk: {summary.risk}/100 · {summary.level}<br/>Officer decision: {state.decision?.status||'Not recorded'}</div><p className="muted">The report includes tender rules, original findings, quoted evidence, document fingerprints, officer reviews and history. Use “Save as PDF” in the print dialog to create a PDF.</p><div className="toolbar"><button className="button primary" onClick={()=>window.print()}><Download size={16}/> Print / Save as PDF</button><button className="button" onClick={exportJson}>Download complete JSON</button></div></Modal>}
 {modal==='decision'&&<Modal title="Record an officer decision" close={()=>setModal(null)}><div className="notice">Automated findings: {summary.fail} failed, {summary.review} need review. {Object.keys(state.reviews).length} of {summary.total} clauses have officer reviews. Your decision is recorded separately; the original analysis is preserved.</div><label className="field">Officer name<input value={officer} onChange={e=>setOfficer(e.target.value)} maxLength={100}/></label><label className="field">Decision<select value={decisionStatus} onChange={e=>setDecisionStatus(e.target.value)}>{['Request clarification','Qualified by officer','Disqualified by officer'].map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Decision rationale<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={3000}/></label><button className="button primary" disabled={!officer.trim()||reason.trim().length<10} onClick={()=>{commit({...state,decision:{status:decisionStatus,reason:reason.trim(),actor:officer.trim(),time:new Date().toISOString()}},'Final officer decision recorded',`${decisionStatus}. ${reason.trim()}`,officer.trim());setModal(null);setReason('');}}>Record decision</button></Modal>}
 {source&&<Modal title={source.doc.name} close={()=>setSource(null)}><div className="toolbar"><label className="field">Page<select value={source.page} onChange={e=>setSource({...source,page:Number(e.target.value),quote:undefined})}>{source.doc.pages.map((_,i)=><option key={i} value={i+1}>Page {i+1}</option>)}</select></label><span className="muted">Extracted text · {source.doc.role==='tender'?'Tender clause':'Bid evidence'}</span></div>{source.quote&&<blockquote className="notice"><mark>{source.quote}</mark></blockquote>}<pre>{source.doc.pages[source.page-1]||'No readable text on this page. Inspect the original document.'}</pre><p className="hash">SHA-256: {source.doc.hash||'Synthetic sample — no source file fingerprint'}</p></Modal>}
 {draft&&<Modal title="Review extracted tender clauses" close={()=>setDraft(null)}><p className="muted">{draft.requirements.length} candidate clauses from {draft.doc.name}. Extraction is rule-based and may miss clauses. Applying replaces existing rules and clears prior reviews. Confirm the full tender separately.</p><div className="draft-list">{draft.requirements.map(r=><div key={r.id}><b>{r.id}</b> {r.title}<small>{r.kind==='minimum'?`Numeric rule: ≥ ${r.minimum} ${r.unit}`:r.kind==='portal'?'External verification required':'Manual review required'} · p. {r.page}</small></div>)}</div><button className="button primary" onClick={()=>{commit(invalidate({...state,requirements:draft.requirements,documents:[...state.documents.filter(d=>d.role!=='tender'),draft.doc]}),'Tender clauses confirmed',`${draft.requirements.length} candidate rules confirmed by local operator; prior reviews cleared.`);setDraft(null);setTab('Requirements');setSelected('');}}>Confirm and apply clauses</button></Modal>}
 {edit&&<Modal title={'Edit rule · '+edit.id} close={()=>setEdit(null)}><form onSubmit={e=>{e.preventDefault();if(!edit.title.trim()||!Number.isFinite(edit.weight)||edit.weight<=0||edit.weight>100)return;if(edit.kind==='minimum'&&(!Number.isFinite(edit.minimum)||edit.minimum!<0))return;commit(invalidate({...state,requirements:state.requirements.map(r=>r.id===edit.id?edit:r)}),'Tender rule edited',`${edit.id}: ${JSON.stringify(state.requirements.find(r=>r.id===edit.id))} → ${JSON.stringify(edit)}. Prior reviews cleared.`);setEdit(null);}}><label className="field">Requirement title<input value={edit.title} required maxLength={240} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><div className="notice">Rule type: {edit.kind}. Source: {edit.source}, page {edit.page}. Unsupported clauses remain manual.</div>{edit.kind==='minimum'&&<label className="field">Minimum ({edit.unit})<input type="number" min="0" step="any" required value={edit.minimum??''} onChange={e=>setEdit({...edit,minimum:e.target.value===''?undefined:Number(e.target.value)})}/></label>}<label className="field">Risk weight (1–100)<input type="number" min="1" max="100" required value={edit.weight} onChange={e=>setEdit({...edit,weight:Number(e.target.value)})}/></label><button className="button primary" type="submit">Save rule and re-evaluate</button></form></Modal>}
 <article className="report"><h1>BIDGUARD · Bid compliance report</h1><p>{state.name} / {state.bidder}</p><p>{state.sample?'SYNTHETIC SAMPLE · ':''}Document-based decision support. No registry verification. Not a certification.</p><p>Compliant: {summary.pass} · Non-compliant: {summary.fail} · Needs review: {summary.review} · Risk: {summary.risk}/100 ({summary.level})</p><p>Risk method: fail = full weight, review = half weight, pass = zero; normalize by total weight. Officer reviews do not change the original index.</p><h2>Officer decision</h2><p>{state.decision?`${state.decision.status} — ${state.decision.actor} — ${state.decision.time}. ${state.decision.reason}`:'No final decision recorded.'}</p>{results.map(r=><section key={r.requirement.id}><h2>{r.requirement.id} · {r.requirement.title}</h2><p>{r.status} — {r.reason}</p><small>Tender source: {r.requirement.source} p. {r.requirement.page} · Rule weight: {r.requirement.weight} · Risk points: {r.risk}</small>{r.evidence.map((e,i)=><blockquote key={i}>{e.document}, p. {e.page}: “{e.quote}”</blockquote>)}{state.reviews[r.requirement.id]&&<p>Officer review: {state.reviews[r.requirement.id].status} — {state.reviews[r.requirement.id].actor}, {state.reviews[r.requirement.id].time}. {state.reviews[r.requirement.id].reason}</p>}</section>)}<h2>Document fingerprints</h2>{state.documents.map(d=><p className="hash" key={d.id}>{d.name}: {d.hash||'Synthetic sample'}</p>)}<h2>Activity history (local, editable storage)</h2>{state.audit.map(a=><p key={a.id}>{a.time} · {a.actor} · {a.action}: {a.detail}</p>)}</article></>;
}
